"use client";
import Image from "next/image";
import { useEffect, useState } from "react";
import { FiShuffle, FiSearch, FiX } from "react-icons/fi";
import { getPokemon } from "@/lib/api";
import { Pokemon } from "@/types";
import { TYPE_COLORS, pokemonArtwork } from "@/constants";
import { formatName, formatHeight, formatWeight } from "@/lib/utils";
import { StatsChart } from "@/components/stats-chart";
import { TypeBadge } from "@/components/type-badge";
import { PageTransition } from "@/components/page-transition";
function Picker({ value, onSelect, onClear }: { value: Pokemon | null; onSelect: (pokemon: Pokemon) => void; onClear: () => void }) { const [query, setQuery] = useState(""); const [suggestions, setSuggestions] = useState<Pokemon[]>([]); useEffect(() => { if (value || query.length < 2) { setSuggestions([]); return; } const timer = window.setTimeout(() => { Promise.all([getPokemon(query).catch(() => null), getPokemon(`${query}1`).catch(() => null), getPokemon(`${query}2`).catch(() => null)]).then((result) => setSuggestions(result.filter((item): item is Pokemon => item !== null).slice(0, 3))); }, 250); return () => window.clearTimeout(timer); }, [query, value]); if (value) return <div className="relative rounded-3xl border border-[var(--line)] bg-[var(--surface-solid)] p-5 text-center"><button onClick={onClear} aria-label="Clear Pokémon" className="absolute right-4 top-4 text-[var(--muted)]"><FiX /></button><div className="relative mx-auto h-48 w-48"><Image src={pokemonArtwork(value.id)} alt={formatName(value.name)} fill sizes="192px" className="object-contain" unoptimized /></div><p className="font-mono text-xs font-bold text-[var(--muted)]">#{String(value.id).padStart(3, "0")}</p><h2 className="mt-1 font-display text-2xl font-bold capitalize">{formatName(value.name)}</h2><div className="mt-3 flex justify-center gap-2">{value.types.map(({ type }) => <TypeBadge key={type.name} type={type.name} />)}</div></div>; return <div className="relative rounded-3xl border border-dashed border-[var(--line)] bg-[var(--surface)] p-6"><div className="relative"><FiSearch className="absolute left-4 top-1/2 -translate-y-1/2 text-[var(--muted)]" /><input autoFocus value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search a Pokémon…" className="h-12 w-full rounded-xl border border-[var(--line)] bg-[var(--surface-solid)] pl-11 pr-3 text-sm outline-none focus:border-[#55c7e8]" /></div>{suggestions.length > 0 && <div className="mt-2 overflow-hidden rounded-xl border border-[var(--line)] bg-[var(--surface-solid)]">{suggestions.map((item) => <button key={item.id} onClick={() => onSelect(item)} className="flex w-full items-center gap-3 px-3 py-2 text-left text-sm font-semibold capitalize hover:bg-[var(--line)]"><img src={item.sprites.front_default ?? ""} alt="" width="36" height="36" />{formatName(item.name)}</button>)}</div>}<p className="mt-5 text-center text-xs font-semibold text-[var(--muted)]">Enter a name or Pokédex number</p></div>; }
export default function ComparePage() { const [left, setLeft] = useState<Pokemon | null>(null); const [right, setRight] = useState<Pokemon | null>(null); return <PageTransition><main className="container-shell py-12 sm:py-16"><div className="text-center"><div className="mx-auto mb-4 inline-flex items-center gap-2 rounded-full bg-[#f0effb] px-3 py-1.5 text-[11px] font-bold uppercase tracking-[.17em] text-[#6c6aa7] dark:bg-[#2d2b4c]"><FiShuffle /> Head to head</div><h1 className="page-heading font-display text-5xl font-bold sm:text-6xl">Compare Pokémon</h1><p className="mx-auto mt-4 max-w-xl prose-copy">Put two Pokémon side by side. Find the stat edge, compare their type identities and choose your next training partner.</p></div><div className="mt-12 grid items-start gap-5 lg:grid-cols-[1fr_auto_1fr]"><Picker value={left} onSelect={setLeft} onClear={() => setLeft(null)} /><div className="hidden h-12 w-12 place-items-center self-center rounded-full bg-[#171d32] font-display text-sm font-bold text-white lg:grid dark:bg-white dark:text-[#171d32]">VS</div><Picker value={right} onSelect={setRight} onClear={() => setRight(null)} /></div>{left && right ? <section className="mt-10 rounded-3xl border border-[var(--line)] bg-[var(--surface-solid)] p-6 shadow-card"><h2 className="font-display text-2xl font-bold">Stat comparison</h2><p className="mt-2 text-sm text-[var(--muted)]">Higher bars indicate a larger base stat, not a guaranteed battle result.</p><div className="mt-7 grid gap-8 md:grid-cols-2"><div><h3 className="mb-5 font-bold capitalize">{formatName(left.name)}</h3><StatsChart stats={left.stats} /></div><div><h3 className="mb-5 font-bold capitalize">{formatName(right.name)}</h3><StatsChart stats={right.stats} /></div></div><div className="mt-8 grid gap-3 border-t border-[var(--line)] pt-6 sm:grid-cols-3"><div className="rounded-2xl bg-[var(--bg)] p-4"><p className="text-xs font-bold uppercase text-[var(--muted)]">Height</p><p className="mt-1 font-bold">{formatHeight(left.height)} <span className="text-[var(--muted)]">vs</span> {formatHeight(right.height)}</p></div><div className="rounded-2xl bg-[var(--bg)] p-4"><p className="text-xs font-bold uppercase text-[var(--muted)]">Weight</p><p className="mt-1 font-bold">{formatWeight(left.weight)} <span className="text-[var(--muted)]">vs</span> {formatWeight(right.weight)}</p></div><div className="rounded-2xl bg-[var(--bg)] p-4"><p className="text-xs font-bold uppercase text-[var(--muted)]">Experience</p><p className="mt-1 font-bold">{left.base_experience ?? "—"} <span className="text-[var(--muted)]">vs</span> {right.base_experience ?? "—"}</p></div></div></section> : <div className="mt-10 rounded-3xl border border-dashed border-[var(--line)] py-16 text-center text-[var(--muted)]">Choose two Pokémon above to begin comparing.</div>}</main></PageTransition>; }
