"use client";
import { useEffect, useMemo, useState } from "react";
import { FiActivity, FiSearch } from "react-icons/fi";
import { getAbility } from "@/lib/api";
import { AbilityDetail } from "@/types";
import { useResourceList } from "@/hooks/use-pokemon";
import { AbilityCard } from "@/components/ability-card";
import { LoadingSkeleton } from "@/components/loading-skeleton";
import { PageTransition } from "@/components/page-transition";
import { useDebounce } from "@/hooks/use-debounce";
export default function AbilitiesPage() { const { data, loading, error } = useResourceList("ability", 100); const [details, setDetails] = useState<AbilityDetail[]>([]); const [query, setQuery] = useState(""); const debounced = useDebounce(query.toLowerCase()); useEffect(() => { if (!data?.results.length) return; let active = true; Promise.all(data.results.slice(0, 48).map((item) => getAbility(item.name).catch(() => null))).then((result) => { if (active) setDetails(result.filter((item): item is AbilityDetail => item !== null)); }); return () => { active = false; }; }, [data]); const visible = useMemo(() => details.filter((item) => item.name.includes(debounced)), [details, debounced]); return <PageTransition><main className="container-shell py-12 sm:py-16"><div className="flex flex-col justify-between gap-7 md:flex-row md:items-end"><div><div className="mb-4 inline-flex items-center gap-2 rounded-full bg-[#f0effb] px-3 py-1.5 text-[11px] font-bold uppercase tracking-[.17em] text-[#6c6aa7] dark:bg-[#2d2b4c]"><FiActivity /> Battle intelligence</div><h1 className="page-heading font-display text-5xl font-bold sm:text-6xl">Abilities</h1><p className="mt-4 max-w-xl prose-copy">The quiet details that change a battle. Browse what Pokémon can do beyond their type and stats.</p></div><div className="relative w-full md:max-w-xs"><FiSearch className="absolute left-4 top-1/2 -translate-y-1/2 text-[var(--muted)]" /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search abilities" className="h-12 w-full rounded-xl border border-[var(--line)] bg-[var(--surface-solid)] pl-11 pr-4 text-sm outline-none focus:border-[#55c7e8]" /></div></div><div className="mt-10 flex items-center justify-between"><p className="text-sm font-semibold text-[var(--muted)]">{data?.count ?? "—"} abilities in the atlas</p><p className="text-xs font-bold uppercase tracking-wider text-[var(--muted)]">Descriptions in English</p></div>{error && <p className="mt-6 rounded-xl bg-[#fff0eb] p-4 text-sm dark:bg-[#3b2531]">{error}</p>}{loading ? <div className="mt-5 grid gap-5 md:grid-cols-2 lg:grid-cols-3"><LoadingSkeleton count={9} /></div> : <div className="mt-5 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{visible.map((ability) => <AbilityCard key={ability.id} ability={ability} />)}</div>}{!loading && !visible.length && <div className="mt-8 rounded-3xl border border-dashed border-[var(--line)] py-16 text-center text-[var(--muted)]">No ability matched “{query}”.</div>}</main></PageTransition>; }
