"use client";

import { TYPE_NAMES, GENERATIONS } from "@/constants";
import { formatName } from "@/lib/utils";

export interface FilterState { generation: string; type: string; height: string; weight: string; sort: "id" | "name" | "height" | "weight"; }

export function Filters({ value, onChange }: { value: FilterState; onChange: (value: FilterState) => void }) {
  const update = (key: keyof FilterState, next: string) => onChange({ ...value, [key]: next });
  return <div className="grid gap-3 rounded-2xl border border-[var(--line)] bg-[var(--surface)] p-3 sm:grid-cols-2 lg:grid-cols-5"><label className="grid gap-1.5 text-xs font-bold uppercase tracking-wider text-[var(--muted)]">Generation<select value={value.generation} onChange={(e) => update("generation", e.target.value)} className="h-11 rounded-xl border border-[var(--line)] bg-[var(--surface-solid)] px-3 text-sm font-semibold normal-case tracking-normal text-[var(--ink)]"><option value="">All generations</option>{GENERATIONS.map((generation, index) => <option key={generation} value={generation}>Generation {index + 1}</option>)}</select></label><label className="grid gap-1.5 text-xs font-bold uppercase tracking-wider text-[var(--muted)]">Type<select value={value.type} onChange={(e) => update("type", e.target.value)} className="h-11 rounded-xl border border-[var(--line)] bg-[var(--surface-solid)] px-3 text-sm font-semibold normal-case tracking-normal text-[var(--ink)]"><option value="">All types</option>{TYPE_NAMES.map((type) => <option key={type} value={type}>{formatName(type)}</option>)}</select></label><label className="grid gap-1.5 text-xs font-bold uppercase tracking-wider text-[var(--muted)]">Height<select value={value.height} onChange={(e) => update("height", e.target.value)} className="h-11 rounded-xl border border-[var(--line)] bg-[var(--surface-solid)] px-3 text-sm font-semibold normal-case tracking-normal text-[var(--ink)]"><option value="">Any height</option><option value="short">Under 0.5 m</option><option value="medium">0.5–1.5 m</option><option value="tall">Over 1.5 m</option></select></label><label className="grid gap-1.5 text-xs font-bold uppercase tracking-wider text-[var(--muted)]">Weight<select value={value.weight} onChange={(e) => update("weight", e.target.value)} className="h-11 rounded-xl border border-[var(--line)] bg-[var(--surface-solid)] px-3 text-sm font-semibold normal-case tracking-normal text-[var(--ink)]"><option value="">Any weight</option><option value="light">Under 10 kg</option><option value="medium">10–50 kg</option><option value="heavy">Over 50 kg</option></select></label><label className="grid gap-1.5 text-xs font-bold uppercase tracking-wider text-[var(--muted)]">Order<select value={value.sort} onChange={(e) => update("sort", e.target.value as FilterState["sort"])} className="h-11 rounded-xl border border-[var(--line)] bg-[var(--surface-solid)] px-3 text-sm font-semibold normal-case tracking-normal text-[var(--ink)]"><option value="id">Pokédex number</option><option value="name">Alphabetical</option><option value="height">Height</option><option value="weight">Weight</option></select></label></div>;
}
