"use client";

import Image from "next/image";
import Link from "next/link";
import { usePathname } from "next/navigation";
import { useState } from "react";
import { FiBookOpen, FiMenu, FiSearch, FiX } from "react-icons/fi";
import { ThemeToggle } from "./theme-toggle";

const links = [{ href: "/pokedex", label: "Pokédex" }, { href: "/types", label: "Types" }, { href: "/abilities", label: "Abilities" }, { href: "/moves", label: "Moves" }, { href: "/regions", label: "Regions" }];
export function Navbar() { const pathname = usePathname(); const [open, setOpen] = useState(false); return <header className="sticky top-0 z-50 border-b border-[var(--line)] bg-[var(--surface)] backdrop-blur-xl"><div className="container-shell flex h-[72px] items-center justify-between gap-5"><Link href="/" onClick={() => setOpen(false)} className="flex shrink-0 items-center gap-2.5" aria-label="PokéAtlas home"><Image src="/brand-mark.svg" alt="" width={36} height={36} priority /><span className="font-display text-xl font-bold tracking-tight">Poké<span className="text-[#e85d68]">Atlas</span></span></Link><nav className="hidden items-center gap-1 lg:flex" aria-label="Main navigation">{links.map((link) => <Link key={link.href} href={link.href} className={`rounded-lg px-3 py-2 text-sm font-semibold transition hover:bg-[var(--line)] ${pathname.startsWith(link.href) ? "text-[#e85d68]" : "text-[var(--muted)]"}`}>{link.label}</Link>)}</nav><div className="flex items-center gap-2"><Link href="/search" aria-label="Search" className="grid h-10 w-10 place-items-center rounded-full border border-[var(--line)] text-lg transition hover:-translate-y-0.5 hover:border-[#e85d68]"><FiSearch /></Link><ThemeToggle /><button className="grid h-10 w-10 place-items-center rounded-full border border-[var(--line)] lg:hidden" onClick={() => setOpen((value) => !value)} aria-label={open ? "Close navigation" : "Open navigation"}>{open ? <FiX /> : <FiMenu />}</button></div></div>{open && <div className="border-t border-[var(--line)] px-5 pb-5 pt-3 lg:hidden"><nav className="container-shell flex flex-col gap-1" aria-label="Mobile navigation">{links.map((link) => <Link key={link.href} onClick={() => setOpen(false)} href={link.href} className={`rounded-xl px-4 py-3 font-semibold ${pathname.startsWith(link.href) ? "bg-[#fff0eb] text-[#e85d68] dark:bg-[#3b2531]" : "text-[var(--muted)]"}`}>{link.label}</Link>)}<Link onClick={() => setOpen(false)} href="/about" className="rounded-xl px-4 py-3 font-semibold text-[var(--muted)]"><FiBookOpen className="mr-2 inline" />About PokéAtlas</Link></nav></div>}</header>; }
