"use client";
import Image from "next/image";
import Link from "next/link";
import { motion } from "framer-motion";
import { FiArrowUpRight } from "react-icons/fi";
import { Pokemon } from "@/types";
import { formatHeight, formatId, formatName, formatWeight } from "@/lib/utils";
import { pokemonArtwork, TYPE_COLORS } from "@/constants";
import { TypeBadge } from "./type-badge";

export function PokemonCard({ pokemon, featured = false }: { pokemon: Pokemon; featured?: boolean }) { const primary = pokemon.types[0]?.type.name ?? "normal"; return <motion.article layout initial={{ opacity: 0, y: 14 }} animate={{ opacity: 1, y: 0 }} whileHover={{ y: -7 }} transition={{ duration: .25 }} className={`group relative overflow-hidden rounded-[1.5rem] border border-[var(--line)] bg-[var(--surface-solid)] shadow-card ${featured ? "md:col-span-2" : ""}`}><div className="absolute -right-8 -top-10 h-36 w-36 rounded-full opacity-50 blur-2xl" style={{ backgroundColor: `${TYPE_COLORS[primary]?.glow ?? TYPE_COLORS.normal.glow}66` }} /><div className="relative flex items-start justify-between p-4"><div><p className="font-mono text-xs font-bold tracking-widest text-[var(--muted)]">{formatId(pokemon.id)}</p><Link href={`/pokemon/${pokemon.id}`} className="mt-1 block font-display text-xl font-bold capitalize tracking-tight hover:text-[#e85d68]">{formatName(pokemon.name)}</Link></div><span className="h-2 w-2 rounded-full bg-[#55c7e8] shadow-[0_0_0_5px_rgba(85,199,232,.12)]" aria-hidden="true" /></div><Link href={`/pokemon/${pokemon.id}`} className="relative block px-5"><div className="relative flex h-40 items-center justify-center overflow-visible"><Image src={pokemonArtwork(pokemon.id)} alt={`${formatName(pokemon.name)} official artwork`} fill sizes="(max-width: 640px) 70vw, 260px" className="poke-card-art object-contain transition duration-500 group-hover:scale-110" unoptimized /></div></Link><div className="relative flex items-end justify-between gap-3 px-5 pb-5 pt-2"><div className="flex flex-wrap gap-1.5">{pokemon.types.map(({ type }) => <TypeBadge key={type.name} type={type.name} />)}</div><Link href={`/pokemon/${pokemon.id}`} aria-label={`Open ${pokemon.name}`} className="grid h-8 w-8 place-items-center rounded-full bg-[var(--bg)] text-[var(--muted)] transition group-hover:bg-[#171d32] group-hover:text-white dark:group-hover:bg-white dark:group-hover:text-[#171d32]"><FiArrowUpRight /></Link></div><div className="flex gap-4 border-t border-[var(--line)] px-5 py-3 text-[10px] font-bold uppercase tracking-wider text-[var(--muted)]"><span>H {formatHeight(pokemon.height)}</span><span>W {formatWeight(pokemon.weight)}</span><span className="ml-auto">{pokemon.base_experience ?? "—"} XP</span></div></motion.article>; }
